version: "3.9"

services:
  rss_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss_bot
    restart: always
    env_file: .env
    volumes:
      - rss_bot_db:/app/data

volumes:
  rss_bot_db:
